//Nested try catch block in try block

class Test4{
	public static void main(String[] args) {
		try{
			try{
				
			}
			catch(ArithmeticException e){
				
			}
		}
		catch(Exception e){
			
		}
	}
}