//Nested try catch block in catch block

class Test5{
	public static void main(String[] args) {
		try{
			}
		catch(Exception e){
			try{
				
			}
			catch(ArithmeticException ae){
				
			}
		}
	}
}